version: '3.7'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: iupa
      MYSQL_PASSWORD: Iupa1234
      MYSQL_DATABASE: diplomatura
    volumes:
      - db_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      #PMA_USER: iupa
      #PMA_PASSWORD: Iupa1234
      PMA_ARBITRARY: 1
    ports:
      - 8000:80
    depends_on:
      - mysql

volumes:
  db_mysql:
